# Generated by Django 4.0.6 on 2022-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
                ('nit', models.PositiveBigIntegerField()),
                ('telefono', models.PositiveBigIntegerField()),
            ],
        ),
    ]
